suumoproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webtestapp.urls'))
]

webtestapp/urls.py
from django.urls import path
from . import views

app_name='webtestapp'

urlpatterns = [
    path('', views.index, name='index'),
]

webtestapp/models.py
from django.db import models

# Create your models here.

webtestapp/forms.py
from django import forms
from django.core.validators import MinValueValidator


TYPE_CHOICES = (
    ('賃貸一戸建て' ,'賃貸一戸建て'),
    ('賃貸マンション' ,'賃貸マンション'),
    ('賃貸テラス、タウンハウス' ,'賃貸テラス、タウンハウス'),
    ('賃貸アパート' ,'賃貸アパート'),
)

WARD_CHOICES = (
       ("中央区","中央区"),
        ("千代田区","千代田区"),
        ("港区","港区"),
        ("新宿区","新宿区"),
        ("文京区","文京区"),
        ("台東区","台東区"),
        ("墨田区","墨田区"),
        ("江東区","江東区"),
        ("品川区","品川区"),
        ("目黒区","目黒区"),
        ("大田区","大田区"),
        ("世田谷区","世田谷区"),
        ("渋谷区","渋谷区"),
        ("中野区","中野区"),
        ("杉並区","杉並区"),
        ("豊島区","豊島区"),
        ("北区","北区"),
        ("荒川区","荒川区"),
        ("板橋区","板橋区"),
        ("練馬区","練馬区"),
        ("足立区","足立区"),
        ("葛飾区","葛飾区"),
        ("江戸川区","江戸川区"),
)

SLDK_CHOICES = (
("K","K"),
("SK","SK"),
("LK","LK"),
("DK","DK"),
("SLK","SLK"),
("SDK","SDK"),
("LDK","LDK"),
("SLDK","SLDK"),
)

class DataForm(forms.Form):
    type = forms.ChoiceField(label="種別",choices=TYPE_CHOICES)
    year = forms.IntegerField(label='築年数',validators=[MinValueValidator(0)])
    stairs = forms.IntegerField(label='階',validators=[MinValueValidator(0)])
    fee = forms.IntegerField(label='管理費',validators=[MinValueValidator(0)])
    area = forms.FloatField(label="専有面積",validators=[MinValueValidator(0)])
    ward = forms.ChoiceField(label='区',choices=WARD_CHOICES)
    station = forms.CharField(label="駅")
    walk = forms.IntegerField(label='歩分',validators=[MinValueValidator(0)])
    fullbasement = forms.IntegerField(label='地下階数',validators=[MinValueValidator(0)])
    fullstairs = forms.IntegerField(label='地上階数',validators=[MinValueValidator(0)])
    rooms = forms.IntegerField(label='居室',validators=[MinValueValidator(0)])
    sldk = forms.ChoiceField(label='SLDK',choices=SLDK_CHOICES)
    

webtestapp/views.py
from django.shortcuts import render,redirect
from .forms import DataForm
from .utils.summo_calculator import calculate
import pandas as pd
import numpy as np
from django.core.cache import cache

def index(request):
    price = 0
    if request.method == 'POST':
        form = DataForm(request.POST)
        if form.is_valid():  # バリデーションを実行
            initial_data = form.cleaned_data  # 送信されたデータを初期値として使用
            form = DataForm(initial=initial_data)  # 初期値付きの新しいフォームを作成
            
            new_data = pd.DataFrame({
                '築年数': np.int16(initial_data['year']),
                '階': np.int32(initial_data['stairs']),
                '管理費': np.int32(initial_data['fee']),
                '専有面積': np.float64(initial_data['area']),
                '区': pd.Categorical([initial_data['ward'],]),
                '最寄り駅': pd.Categorical([initial_data['station'],]),
                '歩分': np.int64(initial_data['walk']),
                '地下階数': np.int64(initial_data['fullbasement']),
                '地上階数': np.int64(initial_data['fullstairs']),
                '居室': np.int64(initial_data['rooms']),
                'S': np.int64(1 if 'S' in initial_data['sldk'] else 0),
                'L': np.int64(1 if 'L' in initial_data['sldk'] else 0),
                'D': np.int64(1 if 'D' in initial_data['sldk'] else 0),
                'K': np.int64(1 if 'K' in initial_data['sldk'] else 0),
                '賃貸アパート': np.bool_('賃貸アパート' == initial_data['type']),
                '賃貸テラス・タウンハウス': np.bool_('賃貸テラス・タウンハウス' == initial_data['type']),
                '賃貸マンション': np.bool_('賃貸マンション' == initial_data['type']),
                '賃貸一戸建て': np.bool_('賃貸一戸建て' == initial_data['type']),
            })
            
            # print(type(initial_data["ward"]))
            # cache.clear()
            price = calculate(new_data)
            dict={
                "price":price
            }
            return render(request,"result.html",dict)
        else:
            # フォームが無効な場合の処理 (エラーメッセージを表示するなど)
            pass
    else:
        form = DataForm()
        
    my_dict = {
        "forms":form,
        "price":price
    }
    
    return render(request,"index.html",my_dict)

templates/index.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>家賃予測アプリ</title>
</head>

<body>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <div class="form">
        <h1 class="title">家賃予測</h1>
        <form action="{% url 'webtestapp:index' %}" method="post">
            {% csrf_token %}
            {% for field in forms %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            </div>
            {% endfor %}
            <input type="submit" value="送信">
        </form>
    </div>
</body>

</html>

templates/result.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>家賃予測アプリ</title>
</head>

<body>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <div>

        <h1 class="price">予想平均価格：{{price}}万円</h1>
        <a href="{% url 'webtestapp:index' %}">再入力</a>
    </div>
</body>

</html>